name: Feature Request
description: State the new feature you wish to add!
title: "[Feature]: <title>"
labels: ["new feature"]
assignees:
  - heartfirey
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: State the new feature you wish to add!
      description: Also tell us, what you want us to optimize?
      placeholder: Tell us what you think!
      value: "I want a new feature for xxx..."
    validations:
      required: true
  - type: textarea
    id: values
    attributes:
      label: What do you think is the value of this feature?
      description: Please describe the audience for this feature and the value of implementing it (why it is needed).
      placeholder: Tell us what you think!
      value: "I want this feature beacause xxx is ..."
    validations:
      required: true
  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important do you think this feature is?
      options:
        - ⭐⭐⭐⭐⭐
        - ⭐⭐⭐⭐
        - ⭐⭐⭐
        - ⭐⭐
        - ⭐
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: You will allow us the right to amend, merge with other questions you submit and incorporate them in development.
      options:
        - label: I agree
          required: true